import { IMAGES } from "@/lib/content";
import type { Pose } from "@/lib/types";

export const MOCK_POSES: Pose[] = [
  {
    id: "1",
    imageUrl: IMAGES.portrait,
    title: "Мягкий портрет у окна",
    keywords: ["portrait", "soft", "window", "портрет", "окно"],
    category: "women",
    shotType: "portrait",
    locations: ["studio", "home"],
    peopleCount: ["1"],
    sessionTypes: ["portrait", "story"],
    styles: ["soft", "minimal"],
    createdAt: "2026-01-01",
  },
  {
    id: "2",
    imageUrl: IMAGES.fullBody,
    title: "Полный рост в движении",
    keywords: ["full body", "dress", "полный рост", "платье"],
    category: "women",
    shotType: "full-body",
    locations: ["street", "park"],
    peopleCount: ["1"],
    sessionTypes: ["fashion", "creative"],
    styles: ["dynamic", "editorial"],
    createdAt: "2026-01-02",
  },
  {
    id: "3",
    imageUrl: "https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=600&h=800&q=80",
    title: "Парная прогулка",
    keywords: ["couple", "love", "пара", "лав"],
    category: "couples",
    shotType: "full-body",
    locations: ["street", "park"],
    peopleCount: ["2"],
    sessionTypes: ["love", "story"],
    styles: ["candid", "cinematic"],
    createdAt: "2026-01-03",
  },
  {
    id: "4",
    imageUrl: "https://images.unsplash.com/photo-1511895426328-dc8714191300?auto=format&fit=crop&w=600&h=800&q=80",
    title: "Семейный кадр на природе",
    keywords: ["family", "семья", "дети"],
    category: "family",
    shotType: "full-body",
    locations: ["park", "nature"],
    peopleCount: ["3+"],
    sessionTypes: ["family"],
    styles: ["candid", "soft"],
    createdAt: "2026-01-04",
  },
  {
    id: "5",
    imageUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=600&h=800&q=80",
    title: "Деловой мужской портрет",
    keywords: ["man", "business", "мужской", "деловой"],
    category: "men",
    shotType: "portrait",
    locations: ["office", "studio"],
    peopleCount: ["1"],
    sessionTypes: ["business", "portrait"],
    styles: ["minimal", "dramatic"],
    createdAt: "2026-01-05",
  },
  {
    id: "6",
    imageUrl: "https://images.unsplash.com/photo-1469334031218-e382a71b716b?auto=format&fit=crop&w=600&h=800&q=80",
    title: "Fashion editorial",
    keywords: ["fashion", "editorial", "мода"],
    category: "women",
    shotType: "full-body",
    locations: ["studio", "street"],
    peopleCount: ["1"],
    sessionTypes: ["fashion"],
    styles: ["editorial", "dramatic"],
    createdAt: "2026-01-06",
  },
];
